# -----------------------------------------------------
#  Copyright Iliass Mahjoub 2023.
#  Distributed under MIT License
#  (See accompanying file LICENSE
#  or copy at http://www.boost.org/LICENSE_1_0.txt)
# -----------------------------------------------------

name: UniversalBareMetal
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  target-ubuntu-stm32f446re-cpp:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        suite: [ all ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo apt install gcc-arm-none-eabi
      - name: target-ubuntu-${{ matrix.suite }}
        working-directory: ./Build/VS
        run: |
          make -f ../Make/make_000.gmk ${{ matrix.suite }} TYP_OS=unix TYP_MCU=stm32f446re_cpp
          ls -la ../Bin/stm32f446re_cpp_x64/stm32f446re.elf ../Bin/stm32f446re_cpp_x64/stm32f446re.hex

  msvc-msbuild-stm32f446re:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        suite: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2
      - name: msvc-msbuild-${{ matrix.suite }}
        shell: cmd
        working-directory: .\Build\VS
        run: |
          MSBuild -m UniversalBareMetal.sln -p:useenv=false -p:Configuration=${{ matrix.suite }} -p:Platform=x64 /t:Rebuild
          dir ..\Bin\${{ matrix.suite }}_x64\UniversalBareMetal.exe

