name: UniversalBareMetal
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  target-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        suite: [ all ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo apt install gcc-arm-none-eabi
      - name: target-ubuntu-${{ matrix.suite }}
        run: |
          make -f ../Make/make_000.gmk ${{ matrix.suite }} TYP_OS=unix
          ls -la ../Bin/Stm32f446re_x64/stm32f446re.elf ../Bin/Stm32f446re_x64/stm32f446re.hex
        working-directory: ./Build/VS
